import '@/lib/firebase-admin';
import type { Metadata } from 'next';
import './globals.css';
import Wrapper from '@/components/global/Wrapper';
import AuthButton from '@/components/global/LoginButton';

export const metadata: Metadata = {
  title: 'Alias',
  description: 'Generated by Loda',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <Wrapper>
          <AuthButton />
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
